extends CanvasLayer
## F1 tuning panel. Every tunable in the game, on a slider, live.
##
## **The panel is generated by reflection, never hand-listed.** It reads
## `get_property_list()` and builds a control for anything marked
## `PROPERTY_USAGE_SCRIPT_VARIABLE` — which is exactly the set of `@export` vars
## a script declares. `@export_group` headers come through as group entries, and
## `@export_range` hints become the slider bounds.
##
## That matters more than it sounds. There are around fifty tunables across
## seven scripts today, and a hand-written panel would be wrong the first time
## either of us added an `@export`. This one cannot drift: add an export, get a
## slider. It also means the *editor* stays the place values are authored — the
## panel is a way to find numbers while playing, not a second source of truth.
##
## **Reflection covers the properties, not the targets.** Which objects appear is
## `_discover()`, and that is hand-written — so a new system with a dozen
## perfectly good `@export`s shows up nowhere until someone adds it here. Three
## did exactly that on 2026-08-31 before anyone noticed. Adding a system is one
## `_collect` call and one Target; if it is an autoload, it has to be named
## directly, because nothing that walks the scene will ever find it.
## Nothing here writes to a scene or to `project.godot`. "Copy changes" puts a
## transcribable list on the clipboard; the inspector is still where a number
## goes to be kept.
##
## Autoloaded as `Debug`, so it exists in every scene including the look-dev
## captures, and no scene file had to be edited to host it.

const SAVE_PATH := "user://tuning.json"
const PANEL_WIDTH := 500.0

## Label on the write-to-project button when there is no plan pending.
const PROJECT_IDLE_TEXT := "Save to project..."
## Plan lines shown in the panel before the rest is left to the console. The
## panel is 500 px of a running game, not a diff viewer.
const PLAN_PREVIEW_LINES := 6
## Wheel suspension and grip are built-in VehicleWheel3D properties, not script
## variables, so they need naming explicitly. These are precisely the numbers
## [[Rover]] flags as tuned-by-reasoning-never-driven.
const WHEEL_PROPERTIES: Array[String] = [
	"suspension_stiffness", "suspension_travel", "suspension_max_force",
	"damping_compression", "damping_relaxation",
	"wheel_friction_slip", "wheel_roll_influence",
	"wheel_radius", "wheel_rest_length",
]


## One tunable group in the panel: where to read values from, and where writes
## go. Reading from a sample and writing to many is what lets "all crates" be a
## single set of sliders rather than six identical copies.
class Target extends RefCounted:
	var title := ""
	var sample: Object = null
	## When set, writes broadcast to every node in this group, re-queried at
	## write time so crates that spawn later are not missed.
	var group := ""
	var nodes: Array = []
	## Explicit property names. Empty means "every script variable".
	var allow: Array[String] = []
	## Rebuild-on-change targets only commit when a drag ends, so dragging a
	## terrain slider does not regenerate the mesh sixty times a second.
	var deferred := false
	## Called on the written object after a change, for values that are consumed
	## once rather than read every frame.
	var after_write := ""

	func writes() -> Array:
		if group != "":
			var found: Array = []
			for n in Engine.get_main_loop().get_nodes_in_group(group):
				found.append(n)
			return found
		return nodes


var _open := false
var _built := false
var _root: PanelContainer
var _rows: VBoxContainer
var _readout: Label
var _status: Label
var _targets: Array[Target] = []
## "Target title/property" -> value as first discovered, for Reset.
var _baseline: Dictionary = {}
## Controls to refresh when a value changes underneath them.
var _sync: Array[Callable] = []
var _restore_mouse := Input.MOUSE_MODE_CAPTURED

var _project_button: Button
var _plan_label: Label
## The pending write-to-project plan. Non-empty means the next click on the
## button commits it; any slider move throws it away, because a plan holds line
## numbers and the value they were resolved against.
var _plan: Array[TuningWriter.Edit] = []


func _ready() -> void:
	layer = 128
	process_mode = Node.PROCESS_MODE_ALWAYS
	visible = false


func _input(event: InputEvent) -> void:
	# _input rather than _unhandled_input: a focused text field would
	# otherwise swallow the key and the panel could not be closed from
	# inside itself.
	if event.is_action_pressed("toggle_debug"):
		toggle()
		get_viewport().set_input_as_handled()


func toggle() -> void:
	set_open(not _open)


func set_open(open: bool) -> void:
	if open == _open:
		return
	_open = open
	if _open:
		_restore_mouse = Input.mouse_mode
		Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
		_rebuild()
	else:
		# Restore whatever the mouse was doing before, so opening the panel
		# while already un-captured does not silently recapture on close.
		Input.mouse_mode = _restore_mouse
	visible = _open


func _process(_delta: float) -> void:
	if not _open or _readout == null:
		return
	_readout.text = _readout_text()


# --- discovery ----------------------------------------------------------

func _discover() -> Array[Target]:
	var out: Array[Target] = []
	var tree := get_tree()

	var planet := Target.new()
	planet.title = "Planet — retunes the world live"
	planet.sample = World
	planet.nodes = [World]
	out.append(planet)

	var astronaut := tree.get_first_node_in_group("player")
	if astronaut != null:
		var t := Target.new()
		t.title = "Astronaut"
		t.sample = astronaut
		t.nodes = [astronaut]
		out.append(t)

		var rigs: Array = []
		_collect(astronaut, "AstronautRig", rigs)
		if not rigs.is_empty():
			var r := Target.new()
			r.title = "Astronaut rig — cycle speeds and stride"
			r.sample = rigs[0]
			r.nodes = rigs
			out.append(r)

	var rover := tree.get_first_node_in_group("rover")
	if rover != null:
		var t := Target.new()
		t.title = "Rover"
		t.sample = rover
		t.nodes = [rover]
		t.after_write = "refresh_load"
		out.append(t)

		var wheels: Array = []
		_collect(rover, "VehicleWheel3D", wheels)
		if not wheels.is_empty():
			var w := Target.new()
			w.title = "Rover wheels — all %d" % wheels.size()
			w.sample = wheels[0]
			w.nodes = wheels
			w.allow = WHEEL_PROPERTIES
			out.append(w)

	var crates := tree.get_nodes_in_group("cargo")
	if not crates.is_empty():
		var t := Target.new()
		t.title = "Cargo — all %d crates" % crates.size()
		t.sample = crates[0]
		t.group = "cargo"
		out.append(t)

	var racks: Array = []
	_collect(tree.current_scene if tree.current_scene != null else tree.root,
		"CargoRack", racks)
	if not racks.is_empty():
		var t := Target.new()
		t.title = "Cargo racks — all %d" % racks.size()
		t.sample = racks[0]
		t.nodes = racks
		out.append(t)

	# Every pad, not the first one in the tree. With a pad per facility, a
	# single-node target silently tunes one of them and leaves the rest alone —
	# the same shape of bug the HUD's delivery receipt had.
	var pads := tree.get_nodes_in_group("delivery")
	if not pads.is_empty():
		var t := Target.new()
		t.title = "Delivery pads — all %d" % pads.size()
		t.sample = pads[0]
		t.group = "delivery"
		out.append(t)

	# The post stack. Its tunables are shader uniforms on a material rather than
	# exports on a script, so they are named explicitly - built from the
	# shader's own uniform list, so this still cannot drift as uniforms change.
	for node in tree.get_nodes_in_group("post"):
		for child in node.get_children():
			var rect := child as ColorRect
			if rect == null:
				continue
			var mat := rect.material as ShaderMaterial
			if mat == null or mat.shader == null:
				continue
			var t := Target.new()
			t.title = "Post — %s" % rect.name
			t.sample = mat
			t.nodes = [mat]
			t.allow = _uniform_names(mat)
			if not t.allow.is_empty():
				out.append(t)

	var terrain: Array = []
	_collect(tree.current_scene if tree.current_scene != null else tree.root,
		"ProceduralTerrain", terrain)
	if not terrain.is_empty():
		var t := Target.new()
		t.title = "Terrain — rebuilds on release"
		t.sample = terrain[0]
		t.nodes = terrain
		t.deferred = true
		out.append(t)

	# The field is a separate target from its tiles. `_collect` matches on a
	# class name, so a TerrainField would otherwise reach nobody — the trap this
	# function's own note is about — while its nine children all turn up above
	# as one "Terrain" group, which is what you want for resolution and relief.
	# Layout is the field's, and only the field has it.
	var field: Array = []
	_collect(tree.current_scene if tree.current_scene != null else tree.root,
		"TerrainField", field)
	if not field.is_empty():
		var t := Target.new()
		t.title = "Terrain field — relays the whole grid, rebuilds on release"
		t.sample = field[0]
		t.nodes = field
		t.deferred = true
		out.append(t)

	var scatter: Array = []
	_collect(tree.current_scene if tree.current_scene != null else tree.root,
		"RockScatter", scatter)
	if not scatter.is_empty():
		var t := Target.new()
		t.title = "Rock scatter — rebuilds on release"
		t.sample = scatter[0]
		t.nodes = scatter
		t.deferred = true
		out.append(t)

	var cursors: Array = []
	_collect(tree.current_scene if tree.current_scene != null else tree.root,
		"PadCursor", cursors)
	if not cursors.is_empty():
		var t := Target.new()
		t.title = "Pad cursor — open a panel to feel it"
		t.sample = cursors[0]
		t.nodes = cursors
		out.append(t)

	var marks: Array = []
	_collect(tree.current_scene if tree.current_scene != null else tree.root,
		"RouteMarks", marks)
	if not marks.is_empty():
		var t := Target.new()
		t.title = "Route marks — the pillar and the scan reveal"
		t.sample = marks[0]
		t.nodes = marks
		out.append(t)

	var maps: Array = []
	_collect(tree.current_scene if tree.current_scene != null else tree.root,
		"MapPanel", maps)
	if not maps.is_empty():
		var t := Target.new()
		t.title = "Map — M to open while tuning"
		t.sample = maps[0]
		t.nodes = maps
		out.append(t)

	var map_terrain: Array = []
	_collect(tree.current_scene if tree.current_scene != null else tree.root,
		"MapTerrain", map_terrain)
	if not map_terrain.is_empty():
		var t := Target.new()
		t.title = "Map relief — rebuilds on release"
		t.sample = map_terrain[0]
		t.nodes = map_terrain
		t.deferred = true
		out.append(t)

	var coverage: Array = []
	_collect(tree.current_scene if tree.current_scene != null else tree.root,
		"CoverageMap", coverage)
	if not coverage.is_empty():
		var t := Target.new()
		t.title = "Coverage — the boundary on the ground"
		t.sample = coverage[0]
		t.nodes = coverage
		# Changing the mask resolution reallocates and repaints it, which is not
		# something to do on every pixel of a slider drag.
		t.deferred = true
		out.append(t)

	# Every sign, not the first one. Same shape as the pads above: a per-site
	# node with a single-node target silently tunes one facility's sign and
	# leaves the rest of the world alone.
	var signs := tree.get_nodes_in_group("site_sign")
	if not signs.is_empty():
		var t := Target.new()
		t.title = "Site signs — all %d, Q to light them" % signs.size()
		t.sample = signs[0]
		t.group = "site_sign"
		out.append(t)

	var scanners: Array = []
	_collect(tree.current_scene if tree.current_scene != null else tree.root,
		"Scanner", scanners)
	if not scanners.is_empty():
		var t := Target.new()
		t.title = "Scanner — Q to ping while tuning"
		t.sample = scanners[0]
		t.nodes = scanners
		out.append(t)

	# The two ledger autoloads, like World above. Neither is a node in the
	# scene, so nothing that walks the tree would ever find them.
	var lattice := Target.new()
	lattice.title = "Lattice — relinks on release"
	lattice.sample = Lattice
	lattice.nodes = [Lattice]
	lattice.deferred = true
	lattice.after_write = "rebuild"
	out.append(lattice)

	var route := Target.new()
	route.title = "Route — the planned trip"
	route.sample = Route
	route.nodes = [Route]
	out.append(route)

	var orders := Target.new()
	orders.title = "Orders — transfer timing"
	orders.sample = Orders
	orders.nodes = [Orders]
	out.append(orders)

	var facilities := tree.get_nodes_in_group("facility")
	if not facilities.is_empty():
		var t := Target.new()
		t.title = "Facilities — all %d" % facilities.size()
		t.sample = facilities[0]
		t.group = "facility"
		out.append(t)

	var relays := tree.get_nodes_in_group("relay")
	if not relays.is_empty():
		var t := Target.new()
		t.title = "Relays — all %d, relinks on release" % relays.size()
		t.sample = relays[0]
		t.group = "relay"
		t.deferred = true
		out.append(t)

	var hud := tree.get_first_node_in_group("hud")
	if hud != null:
		var t := Target.new()
		t.title = "HUD — the speedometer and the controls card"
		t.sample = hud
		t.nodes = [hud]
		out.append(t)

	return out


## Every uniform the material actually exposes, as property names.
func _uniform_names(mat: ShaderMaterial) -> Array[String]:
	var names: Array[String] = []
	for prop in mat.get_property_list():
		var name: String = prop["name"]
		if name.begins_with("shader_parameter/"):
			names.append(name)
	return names


func _collect(n: Node, klass: String, out: Array) -> void:
	if _is_a(n, klass):
		out.append(n)
	for c in n.get_children():
		_collect(c, klass, out)


## Whether `n` is a `klass`, for engine classes and script classes alike.
##
## This used to be an `elif` chain naming every script class the panel knew
## about, so teaching the panel a new system took two edits in two places — and
## making only the obvious one produced a target that silently found nothing.
## Walking the script's own inheritance chain means the panel needs telling
## once.
func _is_a(n: Node, klass: String) -> bool:
	if n.is_class(klass):
		return true
	var script := n.get_script() as Script
	while script != null:
		if script.get_global_name() == klass:
			return true
		script = script.get_base_script()
	return false


## The tunables on `target`, in declaration order, with their group headers.
## Returns dictionaries of {name, type, hint, hint_string, group}.
func _properties_for(target: Target) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	if target.sample == null:
		return out

	var meta := {}
	for prop in target.sample.get_property_list():
		meta[prop["name"]] = prop

	var allowed := {}
	for name in target.allow:
		allowed[name] = true

	# Built-in Node groups ("Transform", "Collision", ...) appear in this list
	# alongside a script's own @export_group entries, so a heading is only
	# emitted once something we are actually showing turns up beneath it, and
	# discarded the moment anything else does. Without that the delivery pad
	# inherits Area3D's "Reverb Bus" as a section title.
	var pending := ""
	var pending_sub := ""
	for prop in target.sample.get_property_list():
		var usage: int = prop["usage"]
		if usage & PROPERTY_USAGE_GROUP:
			pending = prop["name"]
			pending_sub = ""
			continue
		# @export_subgroup arrives as its own entry too, and is neither a group
		# nor a script variable - so before this it fell through to the discard
		# below and the heading simply vanished. The rover's camera levelling
		# knobs sat unlabelled under "Camera" because of it.
		if usage & PROPERTY_USAGE_SUBGROUP:
			pending_sub = prop["name"]
			continue

		var included := false
		if allowed.is_empty():
			# A script's own exports, told apart from the hundred built-ins.
			included = bool(usage & PROPERTY_USAGE_SCRIPT_VARIABLE) \
				and bool(usage & PROPERTY_USAGE_EDITOR)
		else:
			# An explicit list: built-in wheel suspension, or a shader's
			# uniforms, neither of which are script variables.
			included = allowed.has(prop["name"])

		if not included or not _supported(prop["type"]):
			pending = ""
			pending_sub = ""
			continue
		out.append(_entry(prop, pending, pending_sub))
		pending = ""
		pending_sub = ""
	return out


func _entry(prop: Dictionary, group: String, subgroup: String) -> Dictionary:
	return {
		"name": prop["name"],
		"type": prop["type"],
		"hint": prop["hint"],
		"hint_string": prop["hint_string"],
		"group": group,
		"subgroup": subgroup,
	}


func _supported(type: int) -> bool:
	return type in [TYPE_FLOAT, TYPE_INT, TYPE_BOOL, TYPE_VECTOR3, TYPE_COLOR]


# --- value access -------------------------------------------------------

func _read(target: Target, prop: String, component := -1):
	var v = target.sample.get(prop)
	if component >= 0 and v is Vector3:
		return v[component]
	return v


func _write(target: Target, prop: String, value, component := -1) -> void:
	# A plan is a set of line numbers and the values they were resolved against.
	# Touching any slider makes it stale, and a stale plan is the one way this
	# could write a number nobody is looking at.
	_discard_plan()
	for obj in target.writes():
		if obj == null:
			continue
		if component >= 0:
			var vec: Vector3 = obj.get(prop)
			vec[component] = value
			obj.set(prop, vec)
		else:
			obj.set(prop, value)
		if target.after_write != "" and obj.has_method(target.after_write):
			obj.call(target.after_write)


func _key(target: Target, prop: String, component: int) -> String:
	if component < 0:
		return "%s/%s" % [target.title, prop]
	return "%s/%s.%s" % [target.title, prop, "xyz"[component]]


# --- UI -----------------------------------------------------------------

func _rebuild() -> void:
	if not _built:
		_build_shell()
		_built = true
	_targets = _discover()
	_sync.clear()
	for child in _rows.get_children():
		child.queue_free()

	for target in _targets:
		var props := _properties_for(target)
		if props.is_empty():
			continue
		_rows.add_child(_section_label(target.title))
		for p in props:
			var group: String = p["group"]
			if group != "":
				_rows.add_child(_group_label(group))
			var subgroup: String = p["subgroup"]
			if subgroup != "":
				_rows.add_child(_subgroup_label(subgroup))
			match int(p["type"]):
				TYPE_BOOL:
					_rows.add_child(_bool_row(target, p))
				TYPE_COLOR:
					_rows.add_child(_color_row(target, p))
				TYPE_VECTOR3:
					for axis in 3:
						_rows.add_child(_number_row(target, p, axis))
				_:
					_rows.add_child(_number_row(target, p, -1))
	_status.text = "%d groups" % _targets.size()


func _build_shell() -> void:
	_root = PanelContainer.new()
	_root.set_anchors_preset(Control.PRESET_RIGHT_WIDE)
	_root.offset_left = -PANEL_WIDTH - 20.0
	_root.offset_right = -20.0
	_root.offset_top = 20.0
	_root.offset_bottom = -20.0
	var style := StyleBoxFlat.new()
	style.bg_color = Color(0.06, 0.04, 0.05, 0.93)
	style.border_width_left = 2
	style.border_color = Color(1.0, 0.45, 0.28, 0.6)
	style.set_content_margin_all(12.0)
	style.corner_radius_top_left = 3
	style.corner_radius_bottom_left = 3
	_root.add_theme_stylebox_override("panel", style)
	add_child(_root)

	var column := VBoxContainer.new()
	column.add_theme_constant_override("separation", 8)
	_root.add_child(column)

	var title := Label.new()
	title.text = "TUNING  ·  F1 to close"
	title.add_theme_font_size_override("font_size", 13)
	title.add_theme_color_override("font_color", Color(1.0, 0.52, 0.34, 0.95))
	column.add_child(title)

	_readout = Label.new()
	_readout.add_theme_font_size_override("font_size", 13)
	_readout.add_theme_color_override("font_color", Color(0.55, 0.92, 0.88, 0.95))
	column.add_child(_readout)

	var buttons := HBoxContainer.new()
	buttons.add_theme_constant_override("separation", 6)
	column.add_child(buttons)
	buttons.add_child(_button("Reset all", _reset_all))
	buttons.add_child(_button("Copy changes", _copy_changes))
	buttons.add_child(_button("Save session", _save))
	buttons.add_child(_button("Load session", _load))

	# Its own row: this one rewrites source files, and it should not sit in a
	# line of buttons that only move numbers around in memory.
	_project_button = _button(PROJECT_IDLE_TEXT, _save_to_project)
	_project_button.add_theme_color_override("font_color", Color(1.0, 0.72, 0.4))
	column.add_child(_project_button)

	_status = Label.new()
	_status.add_theme_font_size_override("font_size", 12)
	_status.add_theme_color_override("font_color", Color(0.8, 0.82, 0.86, 0.7))
	column.add_child(_status)

	_plan_label = Label.new()
	_plan_label.autowrap_mode = TextServer.AUTOWRAP_OFF
	_plan_label.add_theme_font_size_override("font_size", 11)
	_plan_label.add_theme_color_override("font_color", Color(0.98, 0.86, 0.6, 0.9))
	_plan_label.visible = false
	column.add_child(_plan_label)

	var scroll := ScrollContainer.new()
	scroll.size_flags_vertical = Control.SIZE_EXPAND_FILL
	scroll.horizontal_scroll_mode = ScrollContainer.SCROLL_MODE_DISABLED
	column.add_child(scroll)

	_rows = VBoxContainer.new()
	_rows.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	_rows.add_theme_constant_override("separation", 3)
	scroll.add_child(_rows)

	var footer := Label.new()
	footer.text = ("\"Save session\" keeps values in user:// for this machine. "
		+ "\"Save to project\" writes them back into the .gd, .tscn or .tres "
		+ "they were authored in - shown for review first, then written on a "
		+ "second click.")
	footer.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	footer.add_theme_font_size_override("font_size", 11)
	footer.add_theme_color_override("font_color", Color(0.8, 0.82, 0.86, 0.55))
	column.add_child(footer)


func _button(text: String, handler: Callable) -> Button:
	var b := Button.new()
	b.text = text
	b.add_theme_font_size_override("font_size", 12)
	b.pressed.connect(handler)
	return b


func _section_label(text: String) -> Label:
	var l := Label.new()
	l.text = "\n" + text.to_upper()
	l.add_theme_font_size_override("font_size", 13)
	l.add_theme_color_override("font_color", Color(1.0, 0.62, 0.42, 1.0))
	return l


func _group_label(text: String) -> Label:
	var l := Label.new()
	l.text = "  " + text
	l.add_theme_font_size_override("font_size", 11)
	l.add_theme_color_override("font_color", Color(0.72, 0.62, 0.58, 0.8))
	return l


func _subgroup_label(text: String) -> Label:
	var l := Label.new()
	l.text = "    " + text
	l.add_theme_font_size_override("font_size", 10)
	l.add_theme_color_override("font_color", Color(0.62, 0.54, 0.52, 0.7))
	return l


func _row_label(text: String) -> Label:
	var l := Label.new()
	l.text = text
	l.custom_minimum_size = Vector2(190.0, 0.0)
	l.add_theme_font_size_override("font_size", 12)
	l.add_theme_color_override("font_color", Color(0.87, 0.85, 0.83, 0.9))
	l.tooltip_text = text
	return l


## Shader uniforms are addressed as "shader_parameter/glow_intensity"; only the
## uniform's own name is worth reading on a row.
func _label_for(prop: String, component: int) -> String:
	var name := prop.trim_prefix("shader_parameter/")
	if component < 0:
		return name
	return "%s.%s" % [name, "xyz"[component]]


func _bool_row(target: Target, p: Dictionary) -> HBoxContainer:
	var prop: String = p["name"]
	var row := HBoxContainer.new()
	row.add_child(_row_label(_label_for(prop, -1)))
	var box := CheckBox.new()
	box.button_pressed = bool(_read(target, prop))
	_baseline[_key(target, prop, -1)] = box.button_pressed
	box.toggled.connect(func(on: bool) -> void: _write(target, prop, on))
	row.add_child(box)
	_sync.append(func() -> void: box.set_pressed_no_signal(bool(_read(target, prop))))
	return row


func _color_row(target: Target, p: Dictionary) -> HBoxContainer:
	var prop: String = p["name"]
	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 6)
	row.add_child(_row_label(_label_for(prop, -1)))
	var picker := ColorPickerButton.new()
	picker.color = _read(target, prop)
	picker.edit_alpha = false
	picker.custom_minimum_size = Vector2(120.0, 22.0)
	picker.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	_baseline[_key(target, prop, -1)] = picker.color
	picker.color_changed.connect(func(c: Color) -> void: _write(target, prop, c))
	row.add_child(picker)
	_sync.append(func() -> void: picker.color = _read(target, prop))
	return row


func _number_row(target: Target, p: Dictionary, component: int) -> HBoxContainer:
	var prop: String = p["name"]
	var is_int := int(p["type"]) == TYPE_INT
	var value := float(_read(target, prop, component))
	var bounds := _bounds(p, value)
	var step := 1.0 if is_int else _step(bounds)

	_baseline[_key(target, prop, component)] = _read(target, prop, component)

	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 6)
	row.add_child(_row_label(_label_for(prop, component)))

	var slider := HSlider.new()
	slider.min_value = bounds.x
	slider.max_value = bounds.y
	slider.step = step
	slider.value = value
	slider.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	slider.custom_minimum_size = Vector2(140.0, 0.0)
	row.add_child(slider)

	# A LineEdit rather than a SpinBox. A SpinBox snaps its *display* to its own
	# step, and no single step divides every value cleanly - an authored 32.0 on
	# a 0-60 range showed as 31.998, and 0.35 as 0.35002. Reading a value back
	# wrong is worse than losing the arrows.
	var field := LineEdit.new()
	field.text = _format(value)
	field.custom_minimum_size = Vector2(96.0, 0.0)
	field.alignment = HORIZONTAL_ALIGNMENT_RIGHT
	field.add_theme_font_size_override("font_size", 12)
	row.add_child(field)

	var commit := func(v: float) -> void:
		_write(target, prop, int(round(v)) if is_int else v, component)

	slider.value_changed.connect(func(v: float) -> void:
		field.text = _format(v)
		if not target.deferred:
			commit.call(v)
	)
	if target.deferred:
		# Terrain regenerates a six-figure mesh on every write, so it only gets
		# one when the drag ends.
		slider.drag_ended.connect(func(changed: bool) -> void:
			if changed:
				commit.call(slider.value)
		)

	# Typed entry is deliberately not clamped to the slider: a guessed range is
	# often narrower than a value worth trying, and the slider just pins to its
	# end while the real value goes where it was asked to.
	var submit := func(_text := "") -> void:
		var text := field.text.strip_edges()
		if not text.is_valid_float():
			field.text = _format(float(_read(target, prop, component)))
			return
		var v := text.to_float()
		commit.call(v)
		slider.set_value_no_signal(clampf(v, bounds.x, bounds.y))
		field.text = _format(float(_read(target, prop, component)))

	field.text_submitted.connect(submit)
	field.focus_exited.connect(func() -> void: submit.call())

	_sync.append(func() -> void:
		var current := float(_read(target, prop, component))
		slider.set_value_no_signal(clampf(current, bounds.x, bounds.y))
		field.text = _format(current)
	)
	return row


## Short and exact. String.num with a decimal cap, because GDScript's % format
## has no %g - measured, it raises "unsupported format character" at runtime
## rather than failing to compile. 0.0022 stays 0.0022, 32.0 stays 32.0, and a
## value that runs away to 0.33333333333333 is capped at 0.333333.
func _format(v: float) -> String:
	return String.num(v, 6)


## Slider bounds: the @export_range if the property carries one, otherwise a
## guess around the authored value. A guess that feels wrong is a nudge to put
## a real @export_range in the script, which improves the inspector too.
func _bounds(p: Dictionary, value: float) -> Vector2:
	if int(p["hint"]) == PROPERTY_HINT_RANGE:
		var numbers: Array[float] = []
		for token in String(p["hint_string"]).split(","):
			var t := token.strip_edges()
			if t.is_valid_float():
				numbers.append(t.to_float())
		if numbers.size() >= 2:
			return Vector2(numbers[0], numbers[1])
	if value > 0.0:
		return Vector2(0.0, value * 4.0)
	if value < 0.0:
		return Vector2(value * 4.0, 0.0)
	return Vector2(-1.0, 1.0)


func _step(bounds: Vector2) -> float:
	var span := absf(bounds.y - bounds.x)
	if span <= 0.0:
		return 0.001
	return maxf(span / 1000.0, 0.000001)


# --- readout ------------------------------------------------------------

func _readout_text() -> String:
	var parts := PackedStringArray()
	parts.append("%d fps" % Engine.get_frames_per_second())
	parts.append("g %.2f" % World.surface_gravity)
	var rover := get_tree().get_first_node_in_group("rover") as Rover
	if rover != null:
		parts.append("rover %.1f m/s" % rover.linear_velocity.length())
		var rack := rover.cargo_rack()
		parts.append("jolt %.1f" % rack.jolt())
		if not rack.is_empty():
			parts.append("worst %s" % Crate.label_for(rack.worst_condition()))
	return "   ".join(parts)


# --- buttons ------------------------------------------------------------

func _reset_all() -> void:
	for target in _targets:
		for p in _properties_for(target):
			var prop: String = p["name"]
			if int(p["type"]) == TYPE_VECTOR3:
				for axis in 3:
					var k := _key(target, prop, axis)
					if _baseline.has(k):
						_write(target, prop, _baseline[k], axis)
			else:
				var k := _key(target, prop, -1)
				if _baseline.has(k):
					_write(target, prop, _baseline[k], -1)
	_resync()
	_status.text = "reset to the values the scenes were authored with"


## Everything that differs from what the scene was authored with, in a shape
## that can be read straight across into the inspector.
func _changes() -> Dictionary:
	var out := {}
	for target in _targets:
		for p in _properties_for(target):
			var prop: String = p["name"]
			var components := [0, 1, 2] if int(p["type"]) == TYPE_VECTOR3 else [-1]
			for component in components:
				var k := _key(target, prop, component)
				if not _baseline.has(k):
					continue
				var now = _read(target, prop, component)
				var was = _baseline[k]
				if typeof(now) == TYPE_FLOAT:
					if is_equal_approx(float(now), float(was)):
						continue
				elif now == was:
					continue
				out[k] = {"was": was, "now": now}
	return out


func _copy_changes() -> void:
	var changes := _changes()
	if changes.is_empty():
		_status.text = "nothing changed yet"
		return
	var lines := PackedStringArray()
	lines.append("# Tuning changes — set these in the inspector to keep them")
	for k in changes:
		var c: Dictionary = changes[k]
		lines.append("%-52s %s   (was %s)" % [k, c["now"], c["was"]])
	DisplayServer.clipboard_set("\n".join(lines))
	print("\n".join(lines))
	_status.text = "%d changed value(s) copied to the clipboard" % changes.size()


# --- Writing back to the project ----------------------------------------
##
## Two clicks. The first resolves every changed value to the exact file and line
## it will land on and shows it; the second writes. See [[Debug-Panel]] and
## `tuning_writer.gd` for where a value is considered to live.

func _save_to_project() -> void:
	if _plan.is_empty():
		_make_plan()
	else:
		_commit_plan()


func _make_plan() -> void:
	var entries := _project_entries()
	if entries.is_empty():
		_status.text = "nothing changed yet"
		return

	var writer := TuningWriter.new()
	_plan = writer.plan(entries)

	var writable := 0
	var lines := PackedStringArray()
	for edit in _plan:
		if edit.ok():
			writable += 1
		lines.append(edit.describe())

	print("\n--- Save to project: %d change(s) ---" % _plan.size())
	print("\n".join(lines))

	if writable == 0:
		_status.text = "%d change(s), none of which can be written - see console" \
			% _plan.size()
		_show_plan(lines, false)
		_plan.clear()
		return

	# Only the writable ones survive into the commit, so a value with nowhere to
	# go never silently blocks the rest.
	var keep: Array[TuningWriter.Edit] = []
	for edit in _plan:
		if edit.ok():
			keep.append(edit)
	_plan = keep

	var files := {}
	for edit in _plan:
		files[edit.file] = true
	_status.text = "%d value(s) into %d file(s) - click again to write" \
		% [_plan.size(), files.size()]
	_project_button.text = "Confirm: write %d value(s)" % _plan.size()
	_show_plan(lines, true)


func _commit_plan() -> void:
	var writer := TuningWriter.new()
	var result := writer.apply(_plan)
	var failed: Array = result["failed"]

	print("\n--- Save to project: wrote %d value(s) ---" % result["written"])
	for f: String in result["files"]:
		print("    ", f)
	for f: String in failed:
		print("    FAILED: ", f)

	if result["written"] > 0:
		# The files now say what the sliders say, so nothing is "changed" any
		# more. Without this the next plan would offer to write it all again.
		_rebaseline()
	_discard_plan()

	if failed.is_empty():
		_status.text = "wrote %d value(s) to %d file(s)" \
			% [result["written"], result["files"].size()]
	else:
		_status.text = "wrote %d, %d problem(s) - see console" \
			% [result["written"], failed.size()]


## Every changed property, once per object the panel actually writes to.
##
## Per object and not per target, because a target can broadcast: the six wheels
## are six lines in `rover.tscn`, and tuning them together has to update all
## six. The writer deduplicates whatever collapses onto the same line.
func _project_entries() -> Array:
	var out: Array = []
	for target in _targets:
		var short := _short_title(target)
		for p in _properties_for(target):
			if not _differs(target, p):
				continue
			var prop: String = p["name"]
			for obj in target.writes():
				if obj == null:
					continue
				out.append({
					"obj": obj,
					"prop": prop,
					"label": "%s.%s" % [short, prop.trim_prefix("shader_parameter/")],
				})
	return out


## True when any component of this property differs from the authored value.
func _differs(target: Target, p: Dictionary) -> bool:
	var prop: String = p["name"]
	var components := [0, 1, 2] if int(p["type"]) == TYPE_VECTOR3 else [-1]
	for component in components:
		var k := _key(target, prop, component)
		if not _baseline.has(k):
			continue
		var now = _read(target, prop, component)
		var was = _baseline[k]
		if typeof(now) == TYPE_FLOAT:
			if not is_equal_approx(float(now), float(was)):
				return true
		elif now != was:
			return true
	return false


## "Rover wheels - all 6" becomes "Rover wheels". Titles carry a note after a
## dash for the panel's benefit, which is noise in a file report.
func _short_title(target: Target) -> String:
	var title := target.title
	for marker: String in [" — ", " - "]:
		var at := title.find(marker)
		if at > 0:
			title = title.substr(0, at)
	return title


func _show_plan(lines: PackedStringArray, pending: bool) -> void:
	var shown := lines
	if lines.size() > PLAN_PREVIEW_LINES:
		shown = lines.slice(0, PLAN_PREVIEW_LINES)
		shown.append("... and %d more, in the console"
			% (lines.size() - PLAN_PREVIEW_LINES))
	if pending:
		shown.append("Any slider you touch cancels this.")
	_plan_label.text = "\n".join(shown)
	_plan_label.visible = true


func _discard_plan() -> void:
	if _plan.is_empty() and (_plan_label == null or not _plan_label.visible):
		return
	_plan.clear()
	if _project_button != null:
		_project_button.text = PROJECT_IDLE_TEXT
	if _plan_label != null:
		_plan_label.visible = false


## Re-read every value as the new "authored" baseline, after the files on disk
## have been made to agree with it.
func _rebaseline() -> void:
	for target in _targets:
		for p in _properties_for(target):
			var prop: String = p["name"]
			var components := [0, 1, 2] if int(p["type"]) == TYPE_VECTOR3 else [-1]
			for component in components:
				_baseline[_key(target, prop, component)] = _read(target, prop, component)


func _save() -> void:
	var data := {}
	for target in _targets:
		for p in _properties_for(target):
			var prop: String = p["name"]
			var components := [0, 1, 2] if int(p["type"]) == TYPE_VECTOR3 else [-1]
			for component in components:
				var v = _read(target, prop, component)
				if v is Color:
					v = [v.r, v.g, v.b, v.a]
				data[_key(target, prop, component)] = v
	var f := FileAccess.open(SAVE_PATH, FileAccess.WRITE)
	if f == null:
		_status.text = "could not write %s" % SAVE_PATH
		return
	f.store_string(JSON.stringify(data, "  "))
	f.close()
	_status.text = "saved %d values to %s" % [data.size(), SAVE_PATH]


func _load() -> void:
	if not FileAccess.file_exists(SAVE_PATH):
		_status.text = "no %s yet" % SAVE_PATH
		return
	var f := FileAccess.open(SAVE_PATH, FileAccess.READ)
	var parsed = JSON.parse_string(f.get_as_text())
	f.close()
	if typeof(parsed) != TYPE_DICTIONARY:
		_status.text = "%s is not readable" % SAVE_PATH
		return
	var applied := 0
	for target in _targets:
		for p in _properties_for(target):
			var prop: String = p["name"]
			var components := [0, 1, 2] if int(p["type"]) == TYPE_VECTOR3 else [-1]
			for component in components:
				var k := _key(target, prop, component)
				if not parsed.has(k):
					continue
				var v = parsed[k]
				if int(p["type"]) == TYPE_COLOR:
					if typeof(v) != TYPE_ARRAY or v.size() < 3:
						continue
					_write(target, prop, Color(v[0], v[1], v[2]), component)
				elif int(p["type"]) == TYPE_BOOL:
					_write(target, prop, bool(v), component)
				elif int(p["type"]) == TYPE_INT:
					_write(target, prop, int(v), component)
				else:
					_write(target, prop, float(v), component)
				applied += 1
	_resync()
	_status.text = "loaded %d values from %s" % [applied, SAVE_PATH]


func _resync() -> void:
	for callable in _sync:
		callable.call()
