extends Node3D
## What does get_property_list() actually hand back for our nodes?
##
## The debug panel is generated by reflection rather than hand-listed, so it
## lives or dies on this: which usage flags mark a script's own @export vars,
## whether @export_group survives into the list, and what the built-in wheel
## suspension properties are really called on VehicleWheel3D in 4.7.1.
##
## Runs as a scene.
##   engine/Godot_v4.7.1-stable_win64_console.exe --headless --path game \
##     res://tests/probe_property_list.tscn

const WHEEL_WANTED := [
	"suspension_stiffness", "suspension_travel", "suspension_max_force",
	"damping_compression", "damping_relaxation",
	"wheel_friction_slip", "wheel_roll_influence",
	"wheel_radius", "wheel_rest_length",
]


func _ready() -> void:
	var rover: Rover = load("res://scenes/vehicle/rover.tscn").instantiate()
	add_child(rover)

	print("=== Rover: script variables and groups ===")
	_dump_script_vars(rover)

	var wheels: Array[VehicleWheel3D] = []
	_collect_wheels(rover, wheels)
	print("")
	print("=== VehicleWheel3D: %d found ===" % wheels.size())
	if not wheels.is_empty():
		var w := wheels[0]
		var have := {}
		for prop in w.get_property_list():
			have[prop["name"]] = prop
		for wanted in WHEEL_WANTED:
			if have.has(wanted):
				var p: Dictionary = have[wanted]
				print("  OK      %-24s type=%d hint=%d hint_string=%s value=%s"
					% [wanted, p["type"], p["hint"], p["hint_string"], w.get(wanted)])
			else:
				print("  MISSING %s" % wanted)

	var astronaut: Astronaut = load("res://scenes/player/astronaut.tscn").instantiate()
	add_child(astronaut)
	print("")
	print("=== Astronaut: script variables and groups ===")
	_dump_script_vars(astronaut)

	print("")
	print("=== World autoload: script variables ===")
	_dump_script_vars(World)

	get_tree().quit(0)


func _collect_wheels(n: Node, out: Array[VehicleWheel3D]) -> void:
	var w := n as VehicleWheel3D
	if w != null:
		out.append(w)
	for c in n.get_children():
		_collect_wheels(c, out)


func _dump_script_vars(obj: Object) -> void:
	for prop in obj.get_property_list():
		var usage: int = prop["usage"]
		var pname: String = prop["name"]
		if usage & PROPERTY_USAGE_GROUP:
			print("  [group] %s" % pname)
			continue
		if not (usage & PROPERTY_USAGE_SCRIPT_VARIABLE):
			continue
		if not (usage & PROPERTY_USAGE_EDITOR):
			continue
		print("    %-24s type=%-2d hint=%-2d hint_string=%-18s value=%s"
			% [pname, prop["type"], prop["hint"], prop["hint_string"], obj.get(pname)])
