extends Node3D
## Regression test for the F1 tuning panel.
##
## The panel is generated by reflection, which is what stops it drifting as
## exports are added - and also what makes it fail *quietly*. A filter that
## stops matching, a renamed usage flag, a target that no longer resolves: all
## of them produce an empty panel rather than an error. So this asserts that
## real sliders get built for real properties, that writing through one lands
## on every object it should, and that gravity in particular reaches the
## physics server rather than only the autoload.
##
## Runs as a scene rather than via --script so autoloads exist.
## Run: engine/Godot_v4.7.1-stable_win64_console.exe --headless --path game \
##        res://tests/test_debug_panel.tscn

const WORLD := preload("res://scenes/world/test_world.tscn")
const SETTLE := 90
const FALL_FRAMES := 40
## Gravity to retune to mid-test, well away from the authored 5.39.
const TEST_GRAVITY := 12.0

var _failures: Array[String] = []
var _frames := 0
var _authored_gravity := 0.0
var _faller: RigidBody3D
var _fall_start := 0.0


func _ready() -> void:
	add_child(WORLD.instantiate())
	_authored_gravity = World.surface_gravity


func _physics_process(delta: float) -> void:
	_frames += 1
	match _frames:
		SETTLE:
			_test_discovery()
			_test_subgroups_survive()
			_test_post_target()
			_test_broadcast_write()
			_test_reset()
			_test_gravity_reaches_physics_server()
			_start_fall()
		SETTLE + 1:
			_fall_start = _faller.linear_velocity.y
		SETTLE + FALL_FRAMES:
			_check_fall(delta)
			World.surface_gravity = _authored_gravity
			_finish()


# --- the panel builds something ----------------------------------------

func _test_discovery() -> void:
	Debug.set_open(true)

	var titles := PackedStringArray()
	for t in Debug._targets:
		titles.append(t.title)
	print("targets: %s" % ", ".join(titles))

	_expect(Debug._targets.size() >= 6,
		"only %d targets discovered; expected the planet, astronaut, rover, wheels, cargo, racks and terrain"
		% Debug._targets.size())
	# Discovery is hand-written even though the properties are reflected, so a
	# system with a dozen good @exports can ship reaching nobody. Three did on
	# 2026-08-31 — the scanner, the lattice and the ledger — and the only reason
	# it was noticed is that Mac went looking for a slider. This list is the
	# guard: a system that earns tunables earns a line here.
	for wanted in ["Planet", "Astronaut", "Rover", "wheels", "Cargo", "Post",
			"Terrain", "Scanner", "Lattice", "Orders"]:
		_expect(_has_target(wanted), "no target matching %s was discovered" % wanted)

	_report_unreachable()

	# Sliders, not just headers. Rows include labels, so count the ones that
	# actually carry a control.
	var controls := 0
	for row in Debug._rows.get_children():
		if row is HBoxContainer:
			controls += 1
	print("generated %d tunable rows" % controls)
	_expect(controls >= 40,
		"only %d tunable rows generated from ~50 exports; the reflection filter is dropping things"
		% controls)

	# The wheel target reads built-in properties, not script variables, so it
	# is the one that breaks if the allow-list path regresses.
	var wheels = _target("wheels")
	_expect(wheels != null and Debug._properties_for(wheels).size() >= 8,
		"the wheel target exposed %d properties; suspension and grip are the tunables the Rover note is waiting on"
		% (Debug._properties_for(wheels).size() if wheels != null else -1))


## `@export_subgroup` arrives in `get_property_list()` as its own entry, and is
## neither a group nor a script variable - so it used to fall through to the
## discard that keeps engine headings out, and the heading simply vanished. The
## rover's camera levelling knobs were the first exports to sit under one, and
## they rendered unlabelled beneath "Camera".
##
## Silent, like every other failure in a reflected panel: the sliders were all
## there, just anonymous.
func _test_subgroups_survive() -> void:
	var rover = _target("Rover")
	if rover == null:
		_expect(false, "no rover target to check subgroups on")
		return

	var props := Debug._properties_for(rover)
	var seen_group := false
	var seen_subgroup := false
	var levelling := 0
	for p in props:
		if p["group"] == "Camera":
			seen_group = true
		if p.get("subgroup", "") == "Levelling":
			seen_subgroup = true
		if p["name"] in ["tilt_limit_deg", "tilt_follow", "tilt_smoothing"]:
			levelling += 1

	_expect(seen_group, "the rover's Camera group heading was not emitted")
	_expect(seen_subgroup, "the Levelling subgroup heading was dropped")
	_expect(levelling == 3,
		"%d of the 3 camera levelling knobs reached the panel" % levelling)


## The post stack is the second thing that is not a script variable: its
## tunables are shader uniforms on a ShaderMaterial. If the explicit-list path
## regresses, the whole film look becomes untweakable without an editor restart.
func _test_post_target() -> void:
	var post = _target("Post")
	if post == null:
		_expect(false, "no post target; the film stack is not tweakable from the panel")
		return
	var props := Debug._properties_for(post)
	print("post target exposes %d uniforms" % props.size())
	_expect(props.size() >= 18,
		"post target exposed only %d of the film shader 19 uniforms" % props.size())

	var mat: ShaderMaterial = post.sample
	var before = mat.get_shader_parameter("glow_intensity")
	Debug._write(post, "shader_parameter/glow_intensity", 1.75)
	var after = mat.get_shader_parameter("glow_intensity")
	print("glow_intensity %s -> %s through the panel" % [before, after])
	_expect(is_equal_approx(float(after), 1.75),
		"writing a shader uniform through the panel left it at %s" % after)
	Debug._write(post, "shader_parameter/glow_intensity", before)


# --- writing through one slider hits every object ----------------------

func _test_broadcast_write() -> void:
	var cargo = _target("Cargo")
	if cargo == null:
		_expect(false, "no cargo target to test broadcast writes with")
		return
	var crates := get_tree().get_nodes_in_group("cargo")
	_expect(crates.size() >= 2, "only %d crates; broadcast is not being exercised" % crates.size())

	Debug._write(cargo, "jolt_floor", 33.0)
	var missed := 0
	for c in crates:
		if not is_equal_approx(c.jolt_floor, 33.0):
			missed += 1
	print("broadcast jolt_floor=33 to %d crates, %d missed" % [crates.size(), missed])
	_expect(missed == 0,
		"%d of %d crates did not receive the broadcast write" % [missed, crates.size()])


func _test_reset() -> void:
	Debug._reset_all()
	var crates := get_tree().get_nodes_in_group("cargo")
	var wrong := 0
	for c in crates:
		if not is_equal_approx(c.jolt_floor, 12.0):
			wrong += 1
	_expect(wrong == 0,
		"%d crates kept the tuned jolt_floor after Reset all" % wrong)

	# And a reset must leave nothing reported as changed.
	var changes := Debug._changes()
	_expect(changes.is_empty(),
		"Reset all left %d value(s) still reading as changed" % changes.size())


# --- gravity is the one that has to reach the physics server -----------

func _test_gravity_reaches_physics_server() -> void:
	World.surface_gravity = TEST_GRAVITY
	var space := get_viewport().find_world_3d().space
	var on_server := float(
		PhysicsServer3D.area_get_param(space, PhysicsServer3D.AREA_PARAM_GRAVITY)
	)
	print("set World.surface_gravity=%.2f, physics server reports %.2f"
		% [TEST_GRAVITY, on_server])
	_expect(is_equal_approx(on_server, TEST_GRAVITY),
		"physics server still reports %.2f gravity after retuning to %.2f - rigid bodies would ignore the slider"
		% [on_server, TEST_GRAVITY])


func _start_fall() -> void:
	_faller = RigidBody3D.new()
	_faller.linear_damp_mode = RigidBody3D.DAMP_MODE_REPLACE
	_faller.linear_damp = 0.0
	var col := CollisionShape3D.new()
	var shape := SphereShape3D.new()
	shape.radius = 0.5
	col.shape = shape
	_faller.add_child(col)
	add_child(_faller)
	_faller.global_position = Vector3(0.0, 900.0, 0.0)


## The integration check: a body really does fall faster now.
func _check_fall(delta: float) -> void:
	var measured := absf(_faller.linear_velocity.y - _fall_start) / (delta * (FALL_FRAMES - 2))
	print("a rigid body now falls at %.2f m/s^2 (authored %.2f)"
		% [measured, _authored_gravity])
	_expect(absf(measured - TEST_GRAVITY) < 1.5,
		"body fell at %.2f m/s^2 with gravity retuned to %.2f" % [measured, TEST_GRAVITY])
	_expect(measured > _authored_gravity + 2.0,
		"body fell at %.2f, barely different from the authored %.2f - the slider is not connected"
		% [measured, _authored_gravity])


# --- helpers ------------------------------------------------------------

func _target(fragment: String):
	for t in Debug._targets:
		if t.title.findn(fragment) >= 0:
			return t
	return null


func _has_target(fragment: String) -> bool:
	return _target(fragment) != null


## Everything in the scene carrying its own @export vars that no target covers.
##
## Printed rather than failed: not every tunable belongs on a slider, and a test
## that insisted otherwise would be noise. But the list is what makes the next
## missing system visible without anyone going looking for it.
func _report_unreachable() -> void:
	var covered := {}
	for target in Debug._targets:
		for node in target.nodes:
			covered[node] = true
		if target.group != "":
			for node in get_tree().get_nodes_in_group(target.group):
				covered[node] = true

	var missing := PackedStringArray()
	_walk_for_exports(get_tree().current_scene, covered, missing)
	if missing.is_empty():
		print("every node with its own exports is reachable from the panel")
	else:
		print("NOT on the panel (may be fine): %s" % ", ".join(missing))


func _walk_for_exports(node: Node, covered: Dictionary, out: PackedStringArray) -> void:
	if node == null:
		return
	if not covered.has(node) and _has_own_exports(node):
		var script := node.get_script() as Script
		var name := script.get_global_name() if script != null else node.name
		if not out.has(name):
			out.append(name)
	for child in node.get_children():
		_walk_for_exports(child, covered, out)


func _has_own_exports(node: Node) -> bool:
	if node.get_script() == null:
		return false
	for prop in node.get_property_list():
		var usage := int(prop["usage"])
		if usage & PROPERTY_USAGE_SCRIPT_VARIABLE and usage & PROPERTY_USAGE_EDITOR:
			return true
	return false


func _expect(condition: bool, message: String) -> void:
	if not condition:
		_failures.append(message)


func _finish() -> void:
	if _failures.is_empty():
		print("PASS: the tuning panel discovers, subgroups, writes, resets and retunes gravity.")
		# quit() only schedules the exit, so this must return.
		get_tree().quit(0)
		return
	for f in _failures:
		printerr("FAIL: " + f)
	get_tree().quit(1)
